CI: set -Wno-error=maybe-uninitialized
After the update of msys2-w32api from v11.0.1 to current master (and soon to be v12)
we get: winsup/cygwin/exceptions.cc:1736:33: error: '<anonymous>' may be used uninitialized [-Werror=maybe-uninitialized]

Ignore it like the rest.

Fixes #214